services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/build
      - /app/node_modules
      - /app/.svelte-kit
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: templateuser
      POSTGRES_DB: templateDB
      POSTGRES_PASSWORD: testpassword
    command: ['postgres', '-c', 'listen_addresses=*']
    volumes:
      - ./src/db/database.sql:/docker-entrypoint-initdb.d/baseDB.sql

volumes:
  postgres_data:
